# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a7ef2f7190976a62fe7444c2a5097a6dcc6f7f53f95fe063725c32b910a55ad5e88d7aa759c41a2b773f286e7e9734d175b6a122bec9bf54c06ff5079c7d3be

test:
  secret_key_base: 4480e2c6be82dc4355ee4aae4c6b58a9b4ed51f6bee373ec58f0616dd26d0dd3e21c0f1195b69a8d2f41bbe4fbdbd0c0f0c6fb643be57ea816209e9ff4afdb89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
